### PR TITLE
Task/proguard Added consumerProguardFiles for better optimization

### PR DESCRIPTION
**Pull request by henrytao-me**
Reference can be found here http://stackoverflow.com/questions/26983248/proguard-ignores-config-file-of-library

### CODE REVIEW

**Comment by krisorr** [comment]
@henrytao-me have you verified that the proguard-rules.pro actually work when proguarding an app?  It has been a bit since we have tested that set of rules, they may need updating.

**Comment by henrytao-me** [comment]
Let me verify it on my sample project and get back to you soon.

**Comment by henrytao-me** [comment]
Hi @krisorr, 

I updated proguard-rules. You can checkout the demo at [https://github.com/henrytao-me/mobile-buy-sdk-android/tree/demo](https://github.com/henrytao-me/mobile-buy-sdk-android/tree/demo).

**Comment by henrytao-me** [comment]
Close as out of date

**Pull request closed without merging**
