### PR TITLE
clean up library dependencies

### LINKED ISSUE #255: Conflict between Play Services
The library has a dependency on Play Services 8.40.
Applications using newer versions of Play Services have errors compiling due to conflicts.

Investigate how to work around this.

We have had reports specifically from users with 9.21, but this is likely going to be a general issue going forward.

### LINKED ISSUE #256: Update the version of Play Services
We are currently using 8.4.0 for Wallet services, which is quite old.  We should update to 9.21.

### LINKED ISSUE #277: Fix dependencies
We have compile time dependencies in the buy/build.gradle file that should be moved to the sample application to reduce the number of transitive dependencies we have introduce to users.

```
compile 'com.android.support:design:23.4.0'
compile 'com.android.support:support-v4:23.4.0'
compile 'com.android.support:appcompat-v7:23.4.0'
compile 'com.android.support:palette-v7:23.4.0'
compile 'com.android.support:customtabs:23.4.0'
```

Are all candidates for moving to our sample app build.gradle.

### PR DESCRIPTION
**Pull request by krisorr**
* move assets and resources to the sample directory, they should not have been in the aar
* update the Play Services Library for Wallet to 9.4.0
* update the Support libraries to 23.4.0

resolves #255, resolves #256, resolves #277

@sav007 @yervantk please review

### CODE REVIEW

**Comment by henrytao-me** [comment]
IMO, I suggest we split the library into 2 modules: `com.shopify.mobilebuysdk:core:<version>` and `com.shopify.mobilebuysdk:play-services-wallet:<version>`. It's pretty much like `retrofit2` where they have core module and a bunch of add-ons. Adding unnecessary google play services may end up increasing dex file and tricky in some apps.

**Comment by krisorr** [comment]
@henrytao-me Agreed,  we need to move the Android Pay code out to its own library.  It will most likely not be feasible to do it in the scope of this minor release, and may have to wait for the next one.
It has been on the roadmap, and I created a ticket so we track.
https://github.com/Shopify/mobile-buy-sdk-android/issues/294

**Comment by henrytao-me** [comment]
Nice @krisorr.

**Comment by sav007** [comment]
LGTM

**Comment by yervantk** [comment]
LGTM

**Pull request merged**
