### PR TITLE
Add new api for getting product tags filtered by collection id

### LINKED ISSUE #250: Fetch Tags by collection ID from server
We want to know what tags to show for each collection. Some collections will not have any products with a given tag, so that tag should not be shown. 

The website filters tags through a third party service, which will be difficult to access. 

*We may have to start considering how 3rd party services can be integrated into buy SDK*

@mtaher has indicated that filtering can be done on the server relatively easily.

### PR DESCRIPTION
**Pull request by krisorr**
* Adds a new API that allows you to get Product Tags, but only the ones that are found on Products within the given Collection.
* Updates tests to add the new API
* moves a couple of tests for the Product service to the ProductTest from BuyTest

resolves #250 

@sav007 , @yervantk, @bgulanowski please review.
FYI @gabrieloc

### CODE REVIEW

**Comment by bgulanowski** [comment]
LGTM

**Comment by yervantk** [comment]
LGTM This looks pretty good. Did you have any concerns while you wrote this?

**Comment by krisorr** [comment]
@yervantk ??? like about world hunger or nuclear proliferation?
maybe you could be more specific :)

**Comment by yervantk** [comment]
Do you have any misgivings about adding this into the SDK (even on develop)? Does it interfere with the existing code?

**Comment by krisorr** [comment]
No concerns, it does not interfere or cause issues with existing code or I would not have added it :)

**Pull request merged**
