### PR TITLE
Fastlane

### PR DESCRIPTION
**Pull request by krisorr**
Second try at getting fastlane in.

### CODE REVIEW

**Comment by krisorr** [comment]
@jules2689 - almost working.  I am getting the test xml and my build zip uploaded to artifacts which is good.
How do I go about getting Logcat output as well?

**Comment by jules2689** [comment]
On error, we automatically upload them. Are they useful when there are no errors?

**Comment by krisorr** [comment]
@jules2689 nope, that is fine, thanks for the info.

**Comment by krisorr** [comment]
Going to cheat and merge this PR without review as it is not touching any code.

**Comment by jules2689** [comment]
Is this a good format? `logcat -d -v time > #{log_path}/log_file.txt` or is there anything else you'd like to see there?

**Comment by krisorr** [comment]
That looks good, same as we used to have in buildkite

**Pull request merged**
