### PR TITLE
Refactor/256 update play services library

### LINKED ISSUE #277: Fix dependencies
We have compile time dependencies in the buy/build.gradle file that should be moved to the sample application to reduce the number of transitive dependencies we have introduce to users.

```
compile 'com.android.support:design:23.4.0'
compile 'com.android.support:support-v4:23.4.0'
compile 'com.android.support:appcompat-v7:23.4.0'
compile 'com.android.support:palette-v7:23.4.0'
compile 'com.android.support:customtabs:23.4.0'
```

Are all candidates for moving to our sample app build.gradle.

### PR DESCRIPTION
**Pull request by krisorr**
This PR reverts some of the changes from a previous refactor that broke semantic versioning and would have required a major version bump.
Removing of assets and resources will be dealt with in other PR's.
- moves the resources back into the library
- updates dependencies in library to add back appcompat and design libraries

resolves #305, resolves #277 

@sav007 @yervantk please review

### CODE REVIEW

**Comment by yervantk** [comment]
LGTM

**Comment by davidmuzi** [comment]
Is this still needed? Should be merged or closed

**Comment by krisorr** [comment]
@davidmuzi - agreed, cleaning up tickets and PR's this week, will address this

**Comment by krisorr** [comment]
We will not be merging this PR, the addition of the resources was a bug and they should be removed in this release.

**Pull request closed without merging**
